xetdata/pyxet

- python/pyxet/Cargo.lock
- python/pyxet/pyxet/cli.py
- python/pyxet/pyxet/file_system.py
- python/pyxet/src/lib.rs
This PR adds in a step on a recursive download to fetch the shard hints associated with the destination files.  
It also adds an API for the use to manually specify possible files to dedup against.
> Fetch dedup metadata for existing files on recursive copy

- python/pyxet/pyxet/file_interface.py
Currently many ways to print /write to a pyxet file result in the error "string argument without an encoding"
This allows write() to take a str, in which case it will default convert to utf-8
> Allow printing to file

- python/pyxet/pyxet/commit_transaction.py
- python/pyxet/src/lib.rs
Removed the GIL lock around all the async calls into rust.  This effectively meant that the multithreading on the python end was hobbled, causing non-trivial performance issues.
> Removed GIL around async rust calls.

- python/pyxet/pyxet/cli.py
If a dest directory exists, then the destination path is changed to be inside that directory.  This is wrong.
> Fixed path issue with dest_dir dependent checking.

- python/pyxet/pyxet/file_system.py
Ignores extra slashes in the URL. Fix https://github.com/xetdata/pyxet/issues/49. Also fix for other places that use the same logic.
> ignore extra slashes

- python/pyxet/pyxet/cli.py
On duplicate command check if able to infer a valid user name and if not prompt user to specify a full dest name.
Fix https://github.com/xetdata/xethub/issues/3761
> Check empty user name

- python/pyxet/pyxet/cli.py
- python/pyxet/pyxet/file_system.py
- Fixed issue where branch printing does not list the repo, (it just outputs branch name instead of [user]/[repo]/branch)
- Prepended xet:// to every ls output so that you can just copy and paste entries directly.
- allow 'ls' to work on individual files
> Improved ls output

- python/pyxet/pyxet/cli.py
1. Add "xet://" to `xet branch ls --help`
2. `xet branch ls` output aligns with `xet ls` as in https://github.com/xetdata/pyxet/pull/65
3. Unifies to use `xet://[user]/[repo]`
4. Use term `repo` and `repository` instead of `project`
Fix https://github.com/xetdata/xethub/issues/3889
> Better help messsage and prints

- python/pyxet/pyproject.toml
- python/pyxet/pyxet/cli.py
Loads AWS credentials on s3 access via xet cli iff they are available.
Implies credentials will be loaded if available for both public and private bucket access, not loaded but operation should succeed for public buckets if there aren't any credentials, but fail with no credentials with private bucket with a botocore `PermissionError: Access Denied`.
Enables public s3 bucket access with no credentials.
> only load aws creds when available

- docs/conf.py
- docs/requirements.txt
- python/pyxet/pyxet/cli.py
- python/pyxet/pyxet/file_system.py
We do not import rpyxet if the the SPHINX_BUILD environment variable is set.
> Allow pyxet docs to be buildable without the rust build.

- python/pyxet/pyxet/file_system.py
- python/pyxet/pyxet/util.py
Fixing a bug in https://github.com/xetdata/pyxet/pull/90, didn't set the flag correctly so cache was not disabled, so xet cp download didn't get the maximum speedup.
Confirmed after this fix, downloading 137.9 GB data reaching 4.5 Gbps (bottlenecked by disk) in us-west, matching the previously [benchmarked results](https://www.notion.so/xethub/xet-cp-download-benchmark-655e0d5fa4ea45e5817fee6f99ad8b06).
```
(.env) ubuntu@ip-10-0-27-153:~/data/pyxet/python/pyxet$ time xet cp -r -p 3 xet://XetHub/Llama2/main/models/llama-2-70b-chat ~/data
...
real    4m6.189s
user    2m2.321s 
sys     4m58.232s
```
> fix flags setting bug

- python/pyxet/tests/fsspec_test.py
`fsspec` upgrade in https://github.com/fsspec/filesystem_spec/pull/1329 makes
1. when using a trailing slash in globs, it returns only directories.
2. the double asterisks ** matches 0+ directories.
This PR fix the tests accordingly.
> fix fsspec test due to fsspec upgrade

- .github/workflows/commit.yml
- python/pyxet/pyxet/commit_transaction.py
- python/pyxet/src/transactions.rs
Currently, the transaction limits allow 2048 files per commit, and 8
commits to be in flight at once.  However, analysis of the atomic_commit
function, called to complete a transaction, show that this operation
takes roughly 100-150ms per file present in the transaction.  This
results in the client-side piling up transactions on the server, with
the commits later in the queue not completing before the load balancer
times out.  Reducing these limits is a temporary fix to throttle the
number of commits while still allowing CAS and other file uploads to
proceed in parallel.
> Reduce transaction limits to prevent 504 errors.

- python/pyxet/pyproject.toml
- python/pyxet/pyxet/cli.py
- python/pyxet/pyxet/file_system.py
- python/pyxet/pyxet/sync.py
- python/pyxet/tests/requirements.txt
- python/pyxet/tests/sync_test.py
Fixes: https://github.com/xetdata/xethub/issues/4521
- Adds a flag to `xet sync` (`--update-size`) to update the bucket size of the repo following completion of the sync call.
- Adds a method: `update_size` to XetFS to call Xetea's `/api/xet/repos/<user>/<repo>/bucket_size` url to update the bucket size.
> Add flag to update the source bucket size on Xetea

- docs/index.rst
Says PyXet provides 2 components and then lists 3.
> Fixing typo

- python/pyxet/pyxet/sync.py
- python/pyxet/pyxet/util.py
Some s3 bucket contains entries with names that exactly matches a directory name but is a file. E.g.
```
(.env) di@di-mbp ~ % xet ls s3://1000genomes/alignment_indices/
Key                                                                               LastModified               ETag                                    Size  StorageClass    type        size 
--------------------------------------------------------------------------------  -------------------------  ----------------------------------  --------  --------------  ------  -------- 
1000genomes/alignment_indices/                                                    2013-08-06 16:11:51+00:00  "d41d8cd98f00b204e9800998ecf8427e"         0  STANDARD        file           0
```
This results in bad destination names `.`. See more in …
> filter out invalid s3 files

- python/pyxet/pyxet/cli.py
- python/pyxet/pyxet/sync.py
- python/pyxet/tests/sync_test.py
Support syncing of a single file. For instance:
```
xet sync s3://bucket/a.csv xet://ylow/repo/main
```
Also, --dryrun should print all the copy operations it would have performed. This helps a lot in testing and debugging.
> Support sync of a single file and print dryrun operations

- docs/requirements.txt
Readthedocs build failed (https://readthedocs.org/projects/pyxet/builds/23210757/) because `sphinx-book-theme==0.3.3` requires `sphinx>=3,<5`: 
```
Running Sphinx v4.5.0
Generating for pyxet 0.1.7-rc1
loading translations [en]... done
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/pyxet/envs/latest/lib/python3.11/site-packages/sphinx/registry.py", line 438, in load_extension
metadata = setup(app)
^^^^^^^^^^
File "/home/docs/checkouts/readthedocs.org/user_builds/pyxet/envs/latest/lib/python3.11/site-packages/sphinxcontrib/applehelp/__init__.py", line 230, in setup
app.require_sphinx('5.0')
File "/home/docs/checkouts/readthedocs.org/user_builds/pyxet/envs/latest/lib/python3.11/site-packages/sphinx/application.py", line 393, in require_sphinx
raise …
```
> Fix docs build dep version

- .github/workflows/commit.yml
- python/pyxet/Cargo.lock
- python/pyxet/Cargo.toml
- python/pyxet/pyproject.toml
- python/pyxet/src/lib.rs
This PR ups the version of the xet-core dependency to include the latest features, which also feature global dedup.
> Enabled global dedup

- .github/workflows/commit.yml
- python/pyxet/pyxet/file_system.py
- python/pyxet/pyxet/url_parsing.py
- python/pyxet/tests/cli_cp_test.py
- Fixes bugs in parsing (parsing tests were never actually run)
- Tests now pass.
- Explicit domains are not forced to be xethub.com. 
- Deprecation warnings given now.
> Update URL logic parsing to not force xethub.com as host

- README.md
- docs/index.rst
- docs/markdowns/cli.md
- docs/markdowns/filesystem.md
- docs/markdowns/model_versioning.md
- docs/markdowns/model_versioning_tutorial.md
- docs/markdowns/mount.md
- docs/markdowns/quickstart.md
- docs/markdowns/writing.md
- python/pyxet/pyxet/__init__.py
- python/pyxet/pyxet/cli.py
Ok, based on Hoyt's linear issue, which talks about endpoints, I updated docs in xethub/ and readthedocs here to talk about endpoints. Fixes PRO-46.
In looking for references, I am seeing now that there is inconsistent references in pyxet docs and docstrings. In a git grep of the pyxet repo for `xet://`, I see things like:
```
python/pyxet/pyxet/cli.py:            print("Please specify a valid repository name in format xet://domain:user/repo")
python/pyxet/pyxet/cli.py:            listing = [{'name': "xet://" + path + '/' + n['name'], 'type': 'branch'} for n in listing]
python/pyxet/pyxet/cli.py:    def delete(repo: Annotated[str, typer.Argument(help="Repository name in format xet://domain:user/repo")],
python/pyxet/pyxet/cli.py:                print("Please specify a valid repository …
```
> Update readthedocs to reference endpoints

- python/pyxet/pyxet/__init__.py
- python/pyxet/pyxet/cli.py
- python/pyxet/pyxet/file_operations.py
- python/pyxet/pyxet/file_system.py
- python/pyxet/pyxet/url_parsing.py
- python/pyxet/pyxet/util.py
- python/pyxet/src/lib.rs
- python/pyxet/tests/url_parsing.py
This PR cleans up the doc strings and error messages so that everything is consistent with the new URL format.  In particular, 
- Where the domain should be required, we use `xet://<domain>:<user>/<repo>`
- Where the domain is optional (methods of a XetFS class instantiated with a domain), it is given as `xet://[domain:]<user>/...`
- Required fields are consistently given as `<...>`, and optional fields are given as `[...]`. 
In addition, added in a couple of parsing checks that were not in prior to this.
> Consistent doc strings and error messages for xet:// URLs

- README.md
- docs/index.rst
We moved off of Discord but never updated the Pyxet docs/README.
> Replace Discord references with Slack

- python/pyxet/scripts/build_wheel.sh
./scripts/build_wheel.sh should build the wheel in the same way as needed for distribution.  This adds a flag that is part of the CI build but not in this script.
> Adds missing flags for releasable  process for osx builds.

- python/pyxet/pyxet/url_parsing.py
- python/pyxet/tests/url_parsing.py
This corrects issues when using ports like http://localhost:3000/user.
> Fixes for url parsing around including port in endpoint. 

- python/pyxet/Cargo.lock
- python/pyxet/pyxet/cli.py
- python/pyxet/pyxet/file_system.py
Depends on https://github.com/xetdata/xet-core/pull/391. Fix FUN-90.
Some tests on most used path:
```
(.env) di@di-mbp ~/xetdata/pyxet/python/pyxet % xet ls xet://localhost:3000:seanses-local/comp             
Repository is not accessible to free tier accounts. Upgrade your XetHub subscription to access private repositories: http://localhost:3000///subscription/upgrade.
(.env) di@di-mbp ~/xetdata/pyxet/python/pyxet % xet ls xet://localhost:3000:seanses-local/comp/main
Repository is not accessible to free tier accounts. Upgrade your XetHub subscription to access private repositories: http://localhost:3000///subscription/upgrade.
(.env) di@di-mbp ~/xetdata/pyxet/python/pyxet % xet ls xet://localhost:3000:seanses-local/comp/aomen
Repository is not accessible to free tier accounts. Upgrade …
```
> Show server message on exception

- .github/workflows/commit.yml
- python/pyxet/tests/cli_standalone_cp_tests.py
- python/pyxet/tests/utils.py
Previously, tests were skipped if config stuff was not properly defined, which masked a lot of errors.  This flag, set during the build process, overrides that.
> Adds in a flag, set during github runs, to force all tests to run or error out
