- docs/index.rst
- docs/markdowns/advanced.md
- docs/markdowns/collaboration.md
- docs/markdowns/filesystem.md
- docs/markdowns/integrations.md
- docs/markdowns/model_versioning.md
- docs/markdowns/newrepo.md
- docs/markdowns/quickstart.md
- Cleaned up front page
- Added new repo as a separate section
- Removed mentions to write operations
- Added Hoyt's API docs
> Ann docs edits

- docs/markdowns/integrations.md
- docs/markdowns/newrepo.md
- docs/markdowns/quickstart.md
- Accidentally typed 100TB instead of 1TB in the original docs.
- Update env vars to be `_USER_` format per Slack discussion
> Fix docs, update env vars

- python/pyxet/pyxet/file_system.py
This will allow recursive gets() from root of branches.
> Branches should look like directories

- README.md
Removed some pre 0.1 pyxet language in the README
> docs: updated readme post 0.1

- README.md
Made a different set of changes than I wanted to yesterday! Fixing with this PR
> Added pyxet logo back in and removed construction header

- python/pyxet/pyxet/cli.py
> Revert "Fixed path issue with dest_dir dependent checking."

- python/pyxet/Cargo.lock
- python/pyxet/pyxet/cli.py
- python/pyxet/pyxet/file_system.py
- python/pyxet/src/lib.rs
> Revert "Fetch dedup metadata for existing files on recursive copy"

- python/pyxet/Cargo.lock
Pulls to main at commit https://github.com/xetdata/xet-core/commit/791f2177dcecbee6a0545fdaad904447dbb685cf
> Upgrade git xet core version.

- python/pyxet/README.md
- python/pyxet/docs/markdowns/cli.md
- python/pyxet/docs/markdowns/git.md
- python/pyxet/docs/markdowns/integrations.md
- python/pyxet/docs/markdowns/mount.md
- python/pyxet/docs/markdowns/quickstart.md
- python/pyxet/docs/markdowns/use_cases.md
- python/pyxet/pyxet/README.md
- python/pyxet/pyxet/__init__.py
- python/pyxet/pyxet/cli.py
- python/pyxet/pyxet/commit_transaction.py
- python/pyxet/pyxet/file_interface.py
- python/pyxet/pyxet/file_system.py
- python/pyxet/pyxet/pathlib.py
- python/pyxet/pyxet/url_parsing.py
- python/pyxet/src/lib.rs
- python/pyxet/tests/arrow_test.py
- python/pyxet/tests/file_test.py
- python/pyxet/tests/fsspec_test.py
- python/pyxet/tests/utils.py
Was bothered by all the PEP8 formatting errors and few genuine typos my IDE was showing me so I ran formatting on all the source files I could find.
No functionality change.
> formatting, typos, ide suggestions

- .github/workflows/commit.yml
- python/pyxet/tests/requirements.txt
- tests/arrow_test.py
- tests/file_test.py
- tests/fsspec_test.py
- tests/pandas_test.py
- tests/polars_test.py
- tests/url_tests.py
- tests/utils.py
Commits 1719805ec9b0bd6790dcf5f8bafab5000fc1649b and d3a74750dcd97e7adaf0377aa16c9c7ff889ffcf are accidentally made to main without a PR, this reverts them.
> Revert two commits

- python/pyxet/src/lib.rs
pyxet does not require git config as at most it just clones.
> Remove git user config requirement

- python/pyxet/pyproject.toml
- python/pyxet/pyxet/cli.py
- python/pyxet/pyxet/file_system.py
Repo make now just prints "Public/Private repository created at xet://..."
Fix #76 by making boto3 and botocore a soft dependency
> Fix boto dependencies and repo make printout

- docs/markdowns/cli.md
- python/pyxet/pyxet/cli.py
Add pyxet docs for the `xet sync` command and its limitations.
> Adding docs for xet sync

- python/pyxet/Cargo.lock
- python/pyxet/pyproject.toml
Up xet-core.
Also up fsspec version due to the fsspec upgrade and test changes in https://github.com/xetdata/pyxet/pull/93
> sync xet-core and up fsspec

- python/pyxet/Cargo.lock
- python/pyxet/pyxet/cli.py
- python/pyxet/pyxet/file_operations.py
- python/pyxet/pyxet/util.py
- python/pyxet/tests/cli_cp_test.py
Fix https://github.com/xetdata/xethub/issues/3868
> xet cp source accepts list, supporting real *

- README.md
We have moved to Slack from Discord. Updating the link to our Slack community.
> Update to Slack community

- .github/workflows/commit.yml
- python/pyxet/Cargo.lock
Partly resolves https://github.com/xetdata/xethub/issues/4915
> use rust 1.75.0 and sync xet-core

- python/pyxet/Cargo.lock
Pulls in bugfix for repo salt update.
> Update gitxetcore version

- .github/workflows/commit.yml
- python/pyxet/Cargo.lock
- python/pyxet/src/lib.rs
> Updating git xet core version.

- python/pyxet/Cargo.lock
- python/pyxet/Cargo.toml
- python/pyxet/src/lib.rs
- python/pyxet/src/transactions.rs
Updates the xet-core, this now depends on libxet
> Updated xet-core version, now depends on libxet.

- python/pyxet/develop.sh
- python/pyxet/pyxet/url_parsing.py
- python/pyxet/scripts/run_tests.sh
- python/pyxet/tests/url_parsing.py
Allows domain:port:user to work in xet:// urls. Fix CLI-203
> Fix for domain_user supporting port.

- .github/workflows/commit.yml
- python/pyxet/scripts/build_requirements.txt
- python/pyxet/scripts/build_standalone_cli.sh
- python/pyxet/scripts/build_wheel.sh
- python/pyxet/scripts/cli_requirements.txt
- python/pyxet/scripts/setup_env.sh
- Fixes an issue in which building the standalone cli didn't init the environment properly. 
- Adds tests to make sure scripts are correct.
> Fixes for build standalone cli in release environment.

- python/pyxet/scripts/build_requirements.txt
- python/pyxet/scripts/build_standalone_cli.sh
- python/pyxet/scripts/xet_standalone_entry.py
Fixes issue in which boto3 wasn't packaged with xet cli.
> Added force to ensure pyinstaller packages boto3.
